# Arduino
FROM ros:indigo-rosserial-arduino

MAINTAINER Lionel ATTY <lionel.atty@ign.fr>

# [DEV] Arduino toolkit
RUN apt-get install -y              \
        arduino

CMD ["/bin/bash"]

WORKDIR /root/

